### ISSUE TITLE
Extra nodes

### ISSUE THREAD

**Issue by MaxMaximus** [storj/uplink#1]
Hello 
Does CalcNeededNodes in uplink/storage/segments/store.go still needs to enforce one extra node since erasure code error detection was replaced by pieces hash checks to save egress bandwidth? 

```
func CalcNeededNodes(rs storj.RedundancyScheme) int32 {
	extra := int32(1)

	if rs.OptimalShares > 0 {
		extra = int32(((rs.TotalShares - rs.OptimalShares) * rs.RequiredShares) / rs.OptimalShares)
		if extra == 0 {
			// ensure there is at least one extra node, so we can have error detection/correction
			extra = 1
		}
	}
``` 
Or pieces hash checks apply only to downloads of satellite repairer and uplink still needs to download extra pieces for data integrity check before segment decode?

**Comment by egonelbre** [comment]
Since it's possible to download subranges of the pieces we cannot use piece hashes for them.

The `extra = 1` is also useful for tolerating node failure. However, the `extra` calculation is unlikely to return `0` with production settings anyways, so the `if extra == 0 {` is more of handling test scenarios with low RS numbers.
