### ISSUE TITLE
Determine minimal round trips to do a multipart uploads (current, and theoretical)

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/uplink#114]
It seems like we should be able to start and commit a single segment multipart upload in two round trips. We should even be able to start and commit an inline segment in a single round trip. We should figure out if this is currently the case, and if not, how to do it or why we can't.

**Deliverable**
- some document describing the round trips.

**Comment by azdagron** [comment]
Here is the current state, using the uplink CLI:

### Single Segment (inline)

```
/metainfo.Metainfo/BeginObject
/metainfo.Metainfo/Batch
/metainfo.Metainfo/CommitObject
/metainfo.Metainfo/BeginDeleteObject
/metainfo.Metainfo/BeginDeleteObject
```

### Single Segment (non-inline)

```
/metainfo.Metainfo/BeginObject
/metainfo.Metainfo/BeginSegment
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/metainfo.Metainfo/Batch
/metainfo.Metainfo/CommitObject
/metainfo.Metainfo/BeginDeleteObject
/metainfo.Metainfo/BeginDeleteObject
```

### Two Segments (last inline)

```
/metainfo.Metainfo/BeginObject
/metainfo.Metainfo/BeginSegment
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/metainfo.Metainfo/Batch
/metainfo.Metainfo/Batch
/metainfo.Metainfo/CommitObject
/metainfo.Metainfo/BeginDeleteObject
/metainfo.Metainfo/BeginDeleteObject
```

### Two Segments (none inline)

```
/metainfo.Metainfo/BeginObject
/metainfo.Metainfo/BeginSegment
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/metainfo.Metainfo/Batch
/metainfo.Metainfo/BeginSegment
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/piecestore.Piecestore/Upload
/metainfo.Metainfo/Batch
/metainfo.Metainfo/CommitObject
/metainfo.Metainfo/BeginDeleteObject
/metainfo.Metainfo/BeginDeleteObject
```

The two BeginDeleteObject calls at the end of each are benign calls to the backend to abort the multipart uploads for robustness in the case of failures. They are no-ops since the objects have already been committed. The code in question is part of cmd/uplink and not necessarily a failure of libuplink (though its API does not help here). I have opened https://review.dev.storj.io/c/storj/storj/+/9243 to remove these extraneous RPC calls from cmd/uplink.

**Comment by thepaul** [comment]
Is it implicit here that we're talking about round trips to the satellite, not all round trips?

I think we can leave the storagenode rpcs out.

**Comment by mniewrzal** [comment]
> I think we can leave the storagenode rpcs out.

I agree.

**Comment by azdagron** [comment]
I left them in for completeness, but I can see how that can muddy up the discussion. I'll remove them.

**Comment by Erikvv** [comment]
The sequence diagram for multipart upload at https://github.com/storj/storj/blob/main/docs/blueprints/byte-range-multipart-copy/byte-range-multipart-copy.md#sequence-diagrams is probably helpful

**Comment by mniewrzal** [comment]
One easy thing to reduce roundtrips while upload to satellite would be increasing part size (to 128MiB) in UplinkCLI (atm 64MiB). PartUpload code have an optimization that if we are uploading more than one segment then CommitSegment + BeginSegment will be batched.

**Comment by azdagron** [comment]
Doing any of this is going to be a challenge with the current uplink API. In order to make a good decision here, uplink needs to know the size of the object to be written. The current interface doesn't allow for that. It would be convenient if it took an io.Reader, since an underlying implementation might implement some Sizer or Stater interface. Alternatively, the various uplink methods could take an optional size option in order to make the right decision about the optimal flow to use (and then apply write limits so that the caller cannot exceed the declared size).

**Comment by azdagron** [comment]
I'm a little curious why we're trying to reduce the round trips of small objects (single segment or inline segment), since the guidance from S3 is to not use multipart uploads until your object gets around 100MB or so:

> In general, when your object size reaches 100 MB, you should consider using multipart uploads instead of uploading the object in a single operation.

In any case, from what I can tell, the multipart upload call pattern is not really amenable to reducing round trips to the satellite unless the minio GWs stored state... even then, the GW has no method of knowing how big the object is going to be beforehand...

Maybe I'm misunderstanding the scope of this ticket... are we trying to reduce satellite RPCs from multipart uploads initiated by the GW, or just in general by users of uplink (where we might be able to have more insight into the object being uploaded)?

**Comment by azdagron** [comment]
Talked with Jeff IRL and concluded it's not likely that we'll be able to reduce RPCs for multipart uploads due to the inherent call pattern done by the GW.
