### ISSUE TITLE
Figure out dynamic long tail stuff

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/uplink#120]
Right now we have a overly conservative 29/80 scheme that requires a ton of extra bandwidth. Instead of doing something static, it would be nice if the uplink could communicate with the satellite to get peers dynamically according to the network conditions it is experiencing. For example, if it is uploading many parallel segments, it maybe doesn't need as many extra peers to maintain a good quality of service.

**Deliverable**:
- High level sketch of the API uplinks and satellites would use to get more peers for an ongoing upload
- High level sketch of an idea on how to decide when to get more peers for an ongoing segment upload. For example, maybe always keep an extra 5 peers per segment at all times? It would be nice if different strategies could be simulated or something.

**Comment by azdagron** [comment]
In terms of an API, I think we could get away with adding single RPC, `ExchangeSegmentPieceOrders` or something that allows an uplink to replace piece orders that were originally created by BeginSegment.

The flow could then be as follows:
1. Uplink calls BeginSegment and gets back _total_ orders for the in the redundancy scheme.
2. Instead of using all piece orders to put pieces like it does today, it employs an (as yet undefined) strategy to use a subset, maybe eventually approaching the total if there are failures or long tails.
3. If the segment upload is in danger of failing, because enough pieces have failed, the uplink can call ExchangeSegmentPieceOrders with a list of failed piece numbers and get back an amended list of orders with those pieces replaced. The response includes the modified (and re-signed) segmentID, which contains the piece orders and is verified during CommitSegment.
4. Uplink can use the new piece orders to retry failed pieces.
5. Once it has succeeded, it can call CommitSegment, which will verify the upload results against the signed list of piece orders contained in the segmentID, which is the original, or, if step 3 was exercised, an amended list.

**Comment by azdagron** [comment]
API definition for the new ExchangeSegmentPieceOrders RPC: https://review.dev.storj.io/c/storj/common/+/9371

**Comment by iglesiasbrandon** [comment]
we implemented the RPC for this and have a strategy for the client side. @zeebo @azdagron going to close this issue now!
