### ISSUE TITLE
Created an access grant via AP1 but got a US1 S3 endpoint instead

### ISSUE THREAD

**Issue by weeix** [storj/uplink#94]
Hi,

I created an access grant at https://ap1.storj.io/access-grants and chose to continue in CLI. However, when generating S3 gateway credentials, the CLI returned a US1 endpoint instead of an AP1 endpoint.

![image](https://user-images.githubusercontent.com/6592791/163976494-db5db13e-4110-47f7-ad48-c19a6ab3f28a.png)

- uplink v1.52.2
- Windows 11 Home

**Comment by Erikvv** [comment]
Thanks for your report. This is by design. You can use any Storj-hosted satellite through any Storj-hosted S3-compatible gateway.

If you are in the Asia-pacific region https://gateway.ap1.storjshare.io will probably be fastest for you.

Developer context: this is due to the default auth service set in uplink-cli:
* `--auth-service=https://auth.us1.storjshare.io` set at https://github.com/storj/storj/blob/3f47d19aa6a781a58b3b3c7d3a45557fdfb2edc3/cmd/uplink/cmd_access_setup.go#L35
* `--auth-service=auth.us1.storjshare.io:7777` set at https://github.com/storj/storj/blob/3f47d19aa6a781a58b3b3c7d3a45557fdfb2edc3/cmd/uplink/cmd_access_register.go#L30

So if you really do want the "correct" gateway you can put `./uplink.exe setup --auth-service=https://auth.us1.storjshare.io`
